name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.12.0
homepage: https://github.com/brianegan/chewie

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  video_player: ^1.0.0
  wakelock: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
